version: '3.3'
services:
  mongodb-product-service:
    image: mongo:latest
    container_name: mongodb-product-service
    ports:
      - 27018:27017
    volumes:
      - ./volume/db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=products
    networks:
      - development-network
networks:
 development-network:
   driver: bridge
   
